/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'hello_world.Debug+IOTKit_CM33_VHT' 
 * Target:  'Debug+IOTKit_CM33_VHT' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "IOTKit_CM33.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */


#endif /* RTE_COMPONENTS_H */
