name: 1 matrix job

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - ./**

  push:
    branches: [main]
    paths:
      - ./**

  schedule:
    - cron: '00 22 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      established-runner: ${{ runner.name }}

    strategy:
      fail-fast: false
      matrix:

        compiler: [ 
          {name: AC6,  ext: axf},
          {name: GCC,  ext: elf}
        ]

        target: [
          {type: CMSDK_CM0_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM0plus_VHT,    model: tbd,  board: tbd}, 
          {type: CMSDK_CM3_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM4_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM4_FP_VHT,     model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_SP_VHT,     model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_DP_VHT,     model: tbd,  board: tbd}, 
          {type: IOTKit_CM23_VHT,      model: tbd,  board: tbd}, 
          {type: IOTKit_CM33_VHT,      model: tbd,  board: tbd}, 
          {type: IOTKit_CM33_FP_VHT,   model: tbd,  board: tbd}, 
          {type: ARMCM0,               model: tbd,  board: tbd}, 
          {type: ARMCM0P,              model: tbd,  board: tbd}, 
          {type: ARMCM1,               model: tbd,  board: tbd}, 
          {type: ARMCM3,               model: tbd,  board: tbd}, 
          {type: ARMCM55,              model: tbd,  board: tbd}, 
          {type: ARMCM85,              model: tbd,  board: tbd}
        ]
 
        build: [ 
          {type: Release},
          {type: Debug}
        ]

      max-parallel: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Diagnosis
        run: |
          echo "Info: Selected runner = ${{ runner.name }}"
          echo "Info: Concurrency group = ${{ github.workflow }}-${{ github.ref }}"

      # Build executable for a specific target compiler pair
      - name: Build executable
        id: build_executable
        if: always()
        # Remark regarding the build log redirection (tee command). Do not redirect the build log to the ./out/hello_world/ folder.
        # This folder is currently used by the cbuild process. Access operations to this folder during the build operations will throws errors.
        # The build process creates in ./out/hello_world/ the following subdirectory structure:  /target_type/build_type/compiler_name/
        run: |
            echo "Build executable for a specific target compiler pair "
            cbuild hello_world.csolution.yml --packs --verbose \
                --context hello_world.${{ matrix.build.type }}+${{ matrix.target.type }} \
                --toolchain ${{ matrix.compiler.name }} --rebuild \
                --log ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log

      - name: Error build log
        if: always() && steps.build_executable.outcome != 'success'
        run: |
            # Check if a build exist
            if [ -f ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ]; then
                # Check if the correspond build output directory exist. Special corner case handling i.e. Pack download error.
                if [ ! -d out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}]; then
                  mkdir -p out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}
                fi 
                tree
            else
                touch ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
                mkdir -p out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}
                echo "Error: Build log does not exist!" > ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
                tree
            fi 
            mv ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ./out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}/

      - name: Success build log
        if: steps.build_executable.outcome == 'success'
        run: | 
            mv ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ./out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}/

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
          path: ./out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
          if-no-files-found: ignore

      # Create an artifact directory for the build logs
      - name: Create artifact directory
        if: always()
        run: |
          mkdir -p artifact

      # Download previous generated executables
      - name: Download ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
        id: download_build_logs
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
          path: tmp

      # Move downloaded logs to the artifact folder
      - name: Move downloaded build logs
        id: move_downloaded_build_logs
        if: always()
        run: |
          if [ -f ./tmp/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ]; then
             mv ./tmp/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ./artifact/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ;
          fi

      # Diagnosis: Show the directory structure of artifacts folder
      - name: Show downloaded build logs
        if: always()
        run: |
          echo "Show build log"
          cat ./artifact/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log