name: Hello World example (1 job with sequential step execution)

on:
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - ./**

  push:
    branches: [main]
    paths:    
      - ./**

  schedule:
    - cron: '00 22 * * 0'

jobs:
  install_build_execute:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:

        compiler: [ 
          {name: AC6,  ext: axf},
          {name: GCC,  ext: elf}
        ]

        target: [
          {type: CMSDK_CM0_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM0plus_VHT,    model: tbd,  board: tbd}, 
          {type: CMSDK_CM3_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM4_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM4_FP_VHT,     model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_VHT,        model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_SP_VHT,     model: tbd,  board: tbd}, 
          {type: CMSDK_CM7_DP_VHT,     model: tbd,  board: tbd}, 
          {type: IOTKit_CM23_VHT,      model: tbd,  board: tbd}, 
          {type: IOTKit_CM33_VHT,      model: tbd,  board: tbd}, 
          {type: IOTKit_CM33_FP_VHT,   model: tbd,  board: tbd}, 
          {type: ARMCM0,               model: tbd,  board: tbd}, 
          {type: ARMCM0P,              model: tbd,  board: tbd}, 
          {type: ARMCM1,               model: tbd,  board: tbd}, 
          {type: ARMCM3,               model: tbd,  board: tbd}, 
          {type: ARMCM55,              model: tbd,  board: tbd}, 
          {type: ARMCM85,              model: tbd,  board: tbd}
        ]
 
        build: [ 
          {type: Release},
          {type: Debug}
        ]

      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      # Build executable for a specific target compiler pair
      - name: Build executable
        # Remark regarding the build log redirection (tee command). Do not redirect the build log to the ./out/hello_world/ folder.
        # This folder is currently used by the cbuild process. Access operations to this folder during the build operations will throws errors.
        # The build process creates in ./out/hello_world/ the following subdirectory structure:  /target_type/build_type/compiler_name/
        run: |
            echo "Build executable for a specific target compiler pair "
            cbuild hello_world.csolution.yml --packs --verbose \
                --context hello_world.${{ matrix.build.type }}+${{ matrix.target.type }} \
                --toolchain ${{ matrix.compiler.name }} --rebuild \
                --log ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
            mv ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ./out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}/

            if [ $? -eq 0 ]; then
               echo "Build succeeded"
            else 
               echo "Build failed"
               exit 1
            fi

      # Upload build log
      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
          path: ./out/hello_world/${{ matrix.target.type }}/${{ matrix.build.type }}/${{ matrix.compiler.name }}/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log

      # Create an artifact directory for the logs
      - name: Create artifact directory
        run: |
          mkdir -p artifact

      # Download previous generated executables
      - name: Download ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
          path: tmp

      # Move downloaded logs to the artifact folder
      - name: Move downloaded logs
        run: |        
          mv ./tmp/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log ./artifact/${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log

      # Diagnosis: Show the directory structure of artifacts folder
      - name: Show downloaded logs
        run: |
          echo "Show artifact folder"
          tree artifact
